AWSTemplateFormatVersion: '2010-09-09'
Description: Enable AWS CloudTrail with alerting and a queue for log processing tasks.

Parameters:
  TrailBucketName:
    Description: Name of the S3 bucket to store CloudTrail logs.
    Type: String
    Default: cloudtrail-logs-bucket
    AllowedPattern: "[a-zA-Z0-9.\-_]{3,63}"
    ConstraintDescription: Must be a valid S3 bucket name (3-63 characters).
  AlertEmail:
    Description: Email address to receive notifications when new logs are added.
    Type: String
    AllowedPattern: "^[^@]+@[^@]+\.[^@]+$"
    ConstraintDescription: Must be a valid email address.

Resources:
  CloudTrail:
    Type: "AWS::CloudTrail::Trail"
    Properties:
      IsLogging: true
      S3BucketName: !Ref TrailBucket
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true
      EventSelectors:
        - ReadWriteType: All
          IncludeManagementEvents: true
          DataResources:
            - Type: "AWS::S3::Object"
              Values:
                - "arn:aws:s3:::"

  TrailBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref TrailBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        QueueConfigurations:
          - Event: "s3:ObjectCreated:*"
            Queue: !GetAtt LogProcessingQueue.Arn

  TrailBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudTrail
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Sub "${TrailBucket.Arn}/*"
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
          - Sid: AllowSQSAccess
            Effect: Allow
            Principal:
              Service: "s3.amazonaws.com"
            Action: "sqs:SendMessage"
            Resource: !GetAtt LogProcessingQueue.Arn

  LogProcessingQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: "CloudTrailLogProcessingQueue"

  LogAlertTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "CloudTrailLogAlerts"

  LogAlertSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Protocol: "email"
      TopicArn: !Ref LogAlertTopic
      Endpoint: !Ref AlertEmail

  LogProcessingQueuePolicy:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      Queues:
        - !Ref LogProcessingQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowS3SendMessage
            Effect: Allow
            Principal:
              Service: "s3.amazonaws.com"
            Action: "sqs:SendMessage"
            Resource: !GetAtt LogProcessingQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt TrailBucket.Arn

Outputs:
  CloudTrailBucketName:
    Description: Name of the S3 bucket where CloudTrail logs are stored.
    Value: !Ref TrailBucket

  NotificationTopicARN:
    Description: ARN of the SNS topic for log alerts.
    Value: !Ref LogAlertTopic

  LogProcessingQueueURL:
    Description: URL of the SQS queue for log processing tasks.
    Value: !Ref LogProcessingQueue