AWSTemplateFormatVersion: '2010-09-09'
Description: Enable AWS CloudTrail to capture all API events.

Parameters:
  TrailBucketName:
    Description: Name of the S3 bucket to store CloudTrail logs.
    Type: String
    Default: cloudtrail-logs-bucket
    AllowedPattern: "[a-zA-Z0-9.\-_]{3,63}"
    ConstraintDescription: Must be a valid S3 bucket name (3-63 characters).
  AlertEmail:
    Description: Email address to receive notifications when new logs are added.
    Type: String
    AllowedPattern: "^[^@]+@[^@]+\.[^@]+$"
    ConstraintDescription: Must be a valid email address.


Resources:
  CloudTrail:
    Type: "AWS::CloudTrail::Trail"
    Properties:
      IsLogging: true
      S3BucketName: !Ref TrailBucket
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      EnableLogFileValidation: true
      EventSelectors:
        - ReadWriteType: All
          IncludeManagementEvents: true
          DataResources:
            - Type: "AWS::S3::Object"
              Values:
                - "arn:aws:s3:::"
  TrailBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref TrailBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        TopicConfigurations:
          - Event: "s3:ObjectCreated:*"
            Topic: !Ref LogAlertTopic

  TrailBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudTrail
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Sub "${TrailBucket.Arn}/*"
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
          - Sid: AllowSNSNotification
            Effect: Allow
            Principal:
              Service: "sns.amazonaws.com"
            Action: "s3:GetBucketNotification"
            Resource: !Ref TrailBucket

  LogAlertTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: "CloudTrailLogAlerts"

  LogAlertSubscription:
    Type: "AWS::SNS::Subscription"
    Properties:
      Protocol: "email"
      TopicArn: !Ref LogAlertTopic
      Endpoint: !Ref AlertEmail

Outputs:
  CloudTrailBucketName:
    Description: Name of the S3 bucket where CloudTrail logs are stored.
    Value: !Ref TrailBucket

  
  NotificationTopicARN:
    Description: ARN of the SNS topic for log alerts.
    Value: !Ref LogAlertTopic